general {
    layout = dwindle
    
    allow_tearing = true # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}

dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}


$red        = rgb(f38ba8)
$blue       = rgb(89b4fa)
$sapphire   = rgb(74c7ec)
$sky        = rgb(89dceb)
$teal       = rgb(94e2d5)
$green      = rgb(a6e3a1)
$surface0   = rgb(313244)
$base       = rgb(1e1e2e)

general {
    col.active_border   = $red $green $blue 45deg
    col.inactive_border = $surface0
    border_size         = 2
    gaps_in             = 5
    gaps_out            = 10
}

